server:
  port: 9090
spring:
  redis:
    host: 127.0.0.1
    port: 6379

aliyun:
  # 阿里云的key,需要修改成自己的
  accessKeyId: accessKeyId
  # 阿里云的accessKey密码,创建用户时候要记得保存，否则不见
  accessKeySecret: accessKeySecret
  # 阿里云签名名称
  signName: signName
  # 阿里云模板的code
  templateCode: templateCode
